
const products=[
    {
        id:1,
        name:'KSL01',
        color:'black',
        price:2999,
        rating:4.7,
        src:'/img/Black-1.jpeg'
    },
    {
        id:2,
        name:'KSL02',
        color:'black',
        price:2500,
        rating:4.2,
        src:'/img/Black-2.jpeg'
    },
    {
        id:3,
        name:'KSL03',
        color:'black',
        price:2000,
        rating:3.5,
        src:'/img/Black-3.jpeg'
    },
    {
        id:4,
        name:'KSL04',
        color:'blue',
        price:1500,
        rating:3.9,
        src:'/img/Blue-1.jpeg'
    },
    {
        id:5,
        name:'KWL01',
        color:'blue',
        price:3100,
        rating:4.8,
        src:'/img/Blue-2.jpeg'
    },
    {
        id:6,
        name:'KWL02',
        color:'blue',
        price:1500,
        rating:2.5,
        src:'/img/Blue-3.jpeg'
    },
    {
        id:7,
        name:'KWL03',
        color:'green',
        price:6000,
        rating:4.7,
        src:'/img/Green-1.jpeg'
    },
    {
        id:8,
        name:'KWL04',
        color:'green',
        price:5500,
        rating:4,
        src:'/img/Green-2.jpeg'
    },
    {
        id:9,
        name:'KWL05',
        color:'green',
        price:4500,
        rating:4.9,
        src:'/img/Green-3.jpeg'
    },
    {
        id:10,
        name:'KWL06',
        color:'green',
        price:4500,
        rating:3.8,
        src:'/img/Green-4.jpeg'
    },
    {
        id:11,
        name:'KGL01',
        color:'red',
        price:7800,
        rating:2.9,
        src:'/img/Red-1.jpeg'
    },
    {
        id:12,
        name:'KGL02',
        color:'red',
        price:2900,
        rating:3,
        src:'/img/Red-2.jpeg'
    },
    {
        id:13,
        name:'KGL03',
        color:'white',
        price:7500,
        rating:3.4,
        src:'/img/White-1.jpeg'
    },
    {
        id:14,
        name:'KGL04',
        color:'white',
        price:3000,
        rating:3.8,
        src:'/img/White-2.jpeg'
    }



]

export default products;